name: Continuous Integration
on: 
  push:
    paths-ignore:
    - README.md
  pull-request:
    paths-ignore:
    - README.md

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      name: Checkout Repository
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3

      name: Build, Test
      - run: docker compose up --build test